catalog/urls.py
from django.urls import path

from catalog import views

urlpatterns = [
    path('', views.index, name='index'),

    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('book/create/', views.BookCreateView.as_view(), name='book-create'),
    path('book/<int:pk>/update/', views.BookUpdateView.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDeleteView.as_view(), name='book-delete'),

    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('author/create/', views.AuthorCreateView.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdateView.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDeleteView.as_view(), name='author-delete'),

    path('mybooks/', views.MybookListView.as_view(), name='mybooks'),
    path('borrowed/', views.BorrowedBookListView.as_view(), name='books-borrowed'),

    path('book/<uuid:pk>/renew/', views.renew_book, name='renew-book'),


]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')), # django.contrib.auth.urls -> view

    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),

]

catalog/models.py
from datetime import date
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse

# we've created the Genre as a model
# rather than as free text or a selection list
# so that the possible values can be managed through the database rather than being hard coded.
class Genre(models.Model):
    # Model representing a book genre.
    name = models.CharField(max_length=100, help_text='Enter a book genre (e.g. Science Fiction')

    # String for representing the Model object.
    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=100, help_text='English, French, Korean..')

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True) # if author deleted

    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')

    # first arg is verbose_name
    isbn = models.CharField('ISBN',max_length=13, unique=True,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(Genre, help_text='Select a genre fot this book')

    language = models.ForeignKey(Language, on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        # String for representing the Model object.
        return self.title

    def get_absolute_url(self):
        # Returns the url to access a detail record for this book.
        return reverse('book-detail', args=[str(self.id)])

    def display_genre(self):
       return ', '.join(genre.name for genre in self.genre.all()[:2])


import uuid
class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this book')
    book = models.ForeignKey(Book, on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=100)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('A','Available'),
        ('M','Maintenance'),
        ('O','On loan'),
        ('R','Reserved'),
    )

    status = models.CharField( # in template - get_status_display
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='M',
        help_text='Book availability',
    )

    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ['due_back']
        permissions = (('can_mark_returned','Set book as returned'),)

    def __str__(self):
        return f'{self.id} - {self.book}' # book.title?

    # @property
    def is_overdue(self):
        if self.due_back and date.today() < self.due_back:
            return False
        return True

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name} {self.first_name}'

catalog/forms.py
from django import forms
import datetime

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy

from catalog.models import BookInstance


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text='yyyy-mm-dd (default : 3weeks later)')

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(ugettext_lazy('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(ugettext_lazy('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

class RenewBookModelForm(forms.ModelForm):
    class Meta:
        model = BookInstance
        fields = ['due_back'] # fields = '__all__' or  exclude = '' // but not recommended
        lables = {'due_back':ugettext_lazy('New renewal date')}
        help_text = {'due_back':ugettext_lazy('limit 4 weeks default 3 weeks')}

    def clean_due_back(self):
        data = self.cleaned_data['due_back']
        
        if data < datetime.date.today():
            return ValidationError(ugettext_lazy('Invalid date - renewal in past'))

        if data > datetime.today.today() + datetime.timedelta(weeks=4):
            return ValidationError(ugettext_lazy('Invalid date - renewal more than 4 weeks ahead'))

        return data

catalog/views.py
import datetime

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView

from catalog.forms import RenewBookForm
from catalog.models import Book, BookInstance, Author


permission = [login_required, permission_required('catalog.can_mark_returned', raise_exception=True)]

def index(request):
   num_books = Book.objects.all().count()
   num_instances = BookInstance.objects.all().count()
   num_instances_available = BookInstance.objects.filter(status__exact='A').count()
   num_authors = Author.objects.count() # The 'all()' is implied by default.

   # session
   num_visits = request.session.get('num_visits', 1)
   request.session['num_visits'] = num_visits + 1

   context = {'num_books':num_books,
              'num_instances':num_instances,
              'num_instances_available':num_instances_available,
              'num_authors':num_authors,
              'num_visits':num_visits}

   # Render the HTML template index.html with the data in the context variable
   return render(request,'index.html', context=context)

class BookListView(ListView):
    model = Book
    template_name = 'catalog/book_list.html'
    # paginate_by = 10
    # templates_name = the generic views look for templates in /application_name/the_model_name_list.html
    # context_object_name = book_list or object_list (default)

    # queryset = Book.objects.filter(title__icontains='flower')[:5]
    # def get_queryset(self):
    #     return Book.objects.filter(title__icontains='war')[:5]

    '''
    # to pass additional context variables to the template
    def get_context_data(self, **kwargs):
        book_list_english = Book.objects.filter(language__name__exact='English')
        context = super().get_context_data(**kwargs)
        context['book_list_english'] = book_list_english
        return context
    '''

class BookDetailView(DetailView):
    model = Book
    template_name = 'catalog/book_detail.html'

@method_decorator(permission,'get')
@method_decorator(permission,'post')
class BookCreateView(CreateView):
    model = Book
    fields = '__all__'

@method_decorator(permission,'get')
@method_decorator(permission,'post')
class BookUpdateView(UpdateView):
    model = Book
    fields = '__all__'

@method_decorator(permission,'get')
@method_decorator(permission,'post')
class BookDeleteView(DeleteView):
    model = Book
    success_url = reverse_lazy('book_list')
    template_name = 'catalog/book_delete.html'



class MybookListView(LoginRequiredMixin,ListView):
    models = BookInstance
    template_name = 'catalog/mybook_list.html'

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__iexact='o').order_by('due_back')

@method_decorator(permission,'get')
class BorrowedBookListView(ListView):
    model = BookInstance
    template_name = 'catalog/borrowed_book_list.html'

    def get_queryset(self):
        return BookInstance.objects.filter(status__iexact='o').order_by('due_back')


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookForm(request.POST)

        # Check if the form is valid:
        if form.is_valid(): # clean_renewal_date
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            return HttpResponseRedirect(reverse('books-borrowed'))

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date':proposed_renewal_date})

    context = {'form':form,'book_instance':book_instance}

    return render(request, 'catalog/renew_book.html', context=context )


class AuthorListView(ListView):
    model = Author
    template_name = 'catalog/author_list.html'

    # paginate_by =
    # context_object_name =
    # queryset =
    # def get_queryset(self):
    # def get_context_data(self, **kwargs):


class AuthorDetailView(DetailView):
    model = Author
    template_name = 'catalog/author_detail.html'


# need form - specify fields
@method_decorator(permission,'get')
@method_decorator(permission,'post')
class AuthorCreateView(CreateView):
    model = Author
    fields = ['first_name','last_name','date_of_birth','date_of_death']
    initial = {'date_of_death':'11/06/2020'}
    # template_name = author_form (default)
    # success_url = detail

# need form
@method_decorator(permission,'get')
@method_decorator(permission,'post')
class  AuthorUpdateView(UpdateView):
    model = Author
    fields = '__all__'
    # template_name = author_form (default)
    # success_url = detail

@method_decorator(permission,'get')
@method_decorator(permission,'post')
class AuthorDeleteView(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')
    template_name = 'catalog/author_delete.html'

catalog/templates/catalog/author_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends 'base_generic.html' %}

{% block content %}

<div>
    <div>
        <h1>Author: {{author.last_name}}, {{author.first_name}}</h1>
        <h5>{{author.date_of_birth}}-</h5>
    </div>
    <div>
        <h4>Books</h4>
        {% for book in author.book_set.all %}
        <p><a href="{{ book.get_absolute_url }}">{{book.title}}</a> ({{book.bookinstance_set.all.count}})</p>
        <p>{{book.summary}}</p>
        {% endfor %}
    </div>
</div>

{% endblock %}

catalog/templates/catalog/author_form.html
{% extends 'base_generic.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends 'base_generic.html' %}

{% block content %}

<div>
    <div>
        <h1>Author List</h1>
    </div>
    <div>
        <ul>
            {% for author in author_list %}
            <li><a href="{{ author.get_absolute_url }}">{{author.last_name}}, {{author.first_name}}</a> ({{author.date_of_birth}}~)</li>
            {% endfor %}
        </ul>

    </div>
</div>

{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'A' %}text-success{% elif copy.status == 'M' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'A' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends 'base_generic.html' %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Book List</h1>
  {% if book_list %}
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %} 
{% endblock %}

catalog/templates/catalog/borrowed_book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">
            {{bookinst.book.title}}
        </a>
          ({{ bookinst.due_back }})
          <a href="{% url 'renew-book' bookinst.pk %}">renew</a>
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/mybook_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/renew_book.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}